baseURL = "https://predication.ch"
title = "predication.ch"

disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT", "404"]

[permalinks]
perso = "/:filename/"
eglises = "/:filename/"

[minify]
minifyOutput = true
[minify.tdewolff.html]
keepDocumentTags = true
keepEndTags = true
keepQuotes = true
keepWhitespace = true
